#ifndef CDASHBOARD_H
#define CDASHBOARD_H

#include "CHX711Sensor.h"
#define REMOTEXY_MODE__WIFI_POINT  ///< Use WiFi AP mode for RemoteXY.
#include <WiFi.h>
#include <RemoteXY.h>

#define REMOTEXY_WIFI_SSID "RemoteXY"
#define REMOTEXY_WIFI_PASSWORD "12345678"
#define REMOTEXY_SERVER_PORT 6377

/**
 * @class CDashboard
 * @brief RemoteXY dashboard class handling UI elements for sensor calibration and display.
 */
class CDashboard {
public:
    /**
     * @brief Default constructor.
     * Initializes RemoteXY communication interface.
     */
    CDashboard();

    /**
     * @brief Handles button presses and updates UI elements.
     * @param sensor Reference to the HX711 sensor object.
     */
    void update(CHX711Sensor& sensor);

private:

    /// RemoteXY interface definition (generated by RemoteXY editor).
// RemoteXY GUI configuration  
#pragma pack(push, 1)  
uint8_t RemoteXY_CONF[] =   // 109 bytes
  { 255,3,0,6,0,102,0,19,0,0,0,0,31,1,106,200,1,1,7,0,
  1,6,10,24,24,0,2,31,90,101,114,111,0,1,41,10,24,24,0,2,
  31,69,110,116,101,114,0,1,76,11,24,24,0,2,31,68,65,67,0,68,
  6,108,94,35,1,8,36,74,10,168,89,18,12,2,30,37,64,0,129,27,
  152,56,8,64,17,69,114,114,111,114,32,77,97,115,115,97,103,101,58,32,
  0,66,18,54,66,39,131,2,24 };
  // input variables
  uint8_t buttonZero; // =1 if button pressed, else =0
  uint8_t buttonEnter; // =1 if button pressed, else =0
  uint8_t buttonDAC; // =1 if button pressed, else =0

    // output variables
  float onlineGraphHX711;
  uint8_t StringMessageError; // from 0 to 1
  int8_t levelDac; // from 0 to 100

    // other variable
  uint8_t connect_flag;  // =1 if wire connected, else =0

} RemoteXY;   
#pragma pack(pop)

};

#endif
