/*
   -- HX711Test --
   
   To compile this code using RemoteXY library 3.1.13 or later version 
   download by link http://remotexy.com/en/library/
   To connect using RemoteXY mobile app by link http://remotexy.com/en/download/                   
     - for ANDROID 4.15.01 or later version;
     - for iOS 1.12.1 or later version;
    
   To interact with the GUI, please refer to the manual: 
   https://remotexy.com/ru/help/code/interaction/

   This source code was automatically generated by the RemoteXY editor and 
   is an example for the RemoteXY library. 
   Licensed under the MIT License. See the LICENSE file in the RemoteXY library
   root (https://github.com/RemoteXY/RemoteXY-Arduino-library) for full license 
   details.    
*/

//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////

// you can enable debug logging to Serial at 115200
//#define REMOTEXY__DEBUGLOG    

// RemoteXY select connection mode and include library 
#define REMOTEXY_MODE__WIFI_POINT

#include <WiFi.h>

// RemoteXY connection settings 
#define REMOTEXY_WIFI_SSID "RemoteXY"
#define REMOTEXY_WIFI_PASSWORD "12345678"
#define REMOTEXY_SERVER_PORT 6377


#include <RemoteXY.h>
#include "CHX711.h"
#include "HX711.h"
#include "CEncoder.h"
#include "CMCP4725.h"

// RemoteXY GUI configuration  
#pragma pack(push, 1)  
uint8_t RemoteXY_CONF[] =   // 739 bytes
  { 255,12,0,118,0,220,2,19,0,0,0,0,24,2,106,200,200,84,2,1,
  0,12,0,129,27,152,56,8,2,79,35,5,0,106,69,114,114,111,114,32,
  77,97,115,115,97,103,101,58,32,0,131,90,55,21,33,173,76,26,8,6,
  106,102,24,83,101,116,117,112,0,6,129,227,188,84,12,3,2,54,6,0,
  106,72,88,55,49,49,32,87,101,105,103,104,116,32,105,110,32,107,103,58,
  0,129,243,10,40,14,103,2,65,6,0,106,69,110,99,111,100,101,114,32,
  86,101,108,111,99,105,116,121,32,105,110,32,109,92,47,115,58,0,68,2,
  28,51,129,103,10,96,54,50,25,106,147,108,101,102,116,0,114,105,103,104,
  116,0,68,6,42,96,101,3,10,96,54,51,25,106,147,77,114,97,119,0,
  102,105,108,116,101,114,101,100,32,0,80,68,0,2,8,153,23,52,2,67,
  23,8,1,106,25,24,24,82,65,87,0,79,70,70,0,2,9,160,11,19,
  27,67,23,8,1,106,25,24,24,70,105,108,116,101,114,0,79,70,70,0,
  2,10,164,11,19,52,67,23,8,1,106,25,24,24,80,68,0,79,70,70,
  0,2,20,160,12,19,102,67,23,8,1,106,25,24,24,76,101,102,116,0,
  79,70,70,0,2,33,160,12,19,127,67,23,8,1,106,25,24,24,82,105,
  103,104,116,0,79,70,70,0,67,4,62,38,33,38,77,128,8,0,106,41,
  22,0,130,54,64,21,95,5,35,189,48,11,25,129,226,10,85,14,5,5,
  50,6,0,106,72,88,55,49,49,32,67,97,108,105,98,114,97,116,105,111,
  110,58,0,129,214,14,117,14,7,40,42,6,0,106,70,105,108,116,101,114,
  32,86,97,114,105,97,98,108,101,115,58,0,129,17,14,96,14,55,41,27,
  5,64,106,70,105,108,116,101,114,32,68,101,112,116,104,58,0,4,61,74,
  7,86,90,38,85,8,128,106,29,67,68,74,21,24,175,38,14,10,78,106,
  25,2,129,37,38,65,12,55,53,21,5,64,106,75,112,32,86,97,108,117,
  101,58,0,4,78,40,19,6,90,50,85,8,128,106,29,67,97,33,7,24,
  175,49,14,10,78,106,25,2,129,17,14,96,14,7,51,36,6,0,106,80,
  68,32,86,97,114,105,97,98,108,101,115,58,0,129,46,102,50,12,55,64,
  21,5,64,106,75,100,32,86,97,108,117,101,58,0,4,78,104,19,6,90,
  61,85,8,128,106,29,67,97,98,7,24,175,60,14,10,78,106,25,2,129,
  47,107,50,12,55,74,24,5,64,106,68,101,97,100,98,97,110,100,58,0,
  4,79,109,19,6,90,72,85,8,128,106,29,67,98,102,7,24,175,71,14,
  10,78,106,25,2,131,92,183,14,19,165,4,29,6,6,106,102,24,66,97,
  99,107,0,9,2,4,45,15,21,47,20,72,9,1,106,25,24,24,71,79,
  0,83,116,97,110,100,105,110,103,32,80,111,115,46,0,2,5,50,15,21,
  122,20,72,9,1,106,25,24,24,71,79,0,72,97,110,103,105,110,103,32,
  80,111,115,46,0,67,95,43,7,24,5,11,189,7,0,106,41,2,4,88,
  38,21,5,20,39,9,1,106,25,24,24,71,79,0,83,116,97,114,116,0,
  129,228,126,83,14,7,72,18,6,0,106,79,102,102,115,101,116,58,0 };
  
// this structure defines all the variables and events of your control interface 
struct {

    // input variables
  uint8_t switchRaw; // =1 if switch ON and =0 if OFF
  uint8_t switchFilter; // =1 if switch ON and =0 if OFF
  uint8_t switchPD; // =1 if switch ON and =0 if OFF
  uint8_t switchLeft; // =1 if switch ON and =0 if OFF
  uint8_t switchRight; // =1 if switch ON and =0 if OFF
  int8_t sliderFilter; // from 0 to 100
  int8_t sliderKp; // from 0 to 100
  int8_t sliderKd; // from 0 to 100
  int8_t sliderDeadband; // from 0 to 100
  uint8_t switch_Standing; // =1 if switch ON and =0 if OFF
  uint8_t switch_Hanging; // =1 if switch ON and =0 if OFF
  uint8_t switchStartCal; // =1 if switch ON and =0 if OFF

    // output variables
  float onlineGraphLeftVel;
  float onlineGraphRightVel;
  float onlineGraphRaw;
  float onlineGraphFilter;
  float onlineGraphPD;
  char textError[41]; // string UTF8 end zero
  float valueFilter;
  float valueKp;
  float valueKd;
  float valueDeadband;
  char textCalibration[41]; // string UTF8 end zero

    // other variable
  uint8_t connect_flag;  // =1 if wire connected, else =0

} RemoteXY;   
#pragma pack(pop)
 
/////////////////////////////////////////////
//           END RemoteXY include          //
/////////////////////////////////////////////

HX711 scale;
CHX711 loadcell;
CEncoder leftMotorEncoder;
CEncoder rightMotorEncoder;
CMCP4725 dac;

uint8_t loadcellDataPin = 4;
uint8_t loadcellClockPin = 5;

// === Encoder Pins ===
uint8_t pinLeftEncoderA  = 15;
uint8_t pinLeftEncoderB  = 16;
uint8_t pinRightEncoderA = 17;
uint8_t pinRightEncoderB = 18;

uint8_t dacDataPin = 6;
uint8_t dacClockPin = 7;
uint8_t dacInputPin = 40;

bool start = false;
bool tared = false;

bool raw = false;
bool filter = false;
bool pid = false;

float pidValue = 0;
float filterValue = 0;
float rawValue = 0;

float normKp = 0;
float normKd = 0;

float dacInput = 0;

char startText[] = "Start Calibration:put HTA on Wheels";
char tareText[] = "Tared: hold HTA vertical on CAL point";
char doneText[] = "Calibration done";

char ErrorCalOrder[] = "Error in calibration order";

void setup() 
{
  WiFi.mode(WIFI_AP);
  WiFi.softAP(REMOTEXY_WIFI_SSID, REMOTEXY_WIFI_PASSWORD, 6); // oder 11
  RemoteXY_Init();

  loadcell.setup(loadcellDataPin, loadcellClockPin);
  leftMotorEncoder.setup(pinLeftEncoderA, pinLeftEncoderB);
  rightMotorEncoder.setup(pinRightEncoderA, pinRightEncoderB);
  dac.setupDout(dacDataPin, dacClockPin);
  // TODO you setup code
  WiFi.setAutoReconnect(true);
} .

void loop() 
{ 
  RemoteXY_Handler ();


  // Handle RAW//////
  if (RemoteXY.switchRaw){
    rawValue = loadcell.getRaw();
    RemoteXY.onlineGraphRaw = rawValue;
    raw = true;
  }
  else {
    RemoteXY.onlineGraphRaw = 0;
    raw = false;
  }
  
    // Handle Filter//////
  if (RemoteXY.switchFilter){
    RemoteXY.valueFilter = map(RemoteXY.sliderFilter, 0, 100, 2, 50);
    
    filterValue = loadcell.getFiltered(RemoteXY.valueFilter);
    RemoteXY.onlineGraphFilter = filterValue;
    filter = true;
  }
  else {
    RemoteXY.onlineGraphFilter = 0;
    RemoteXY.sliderFilter = 0;
    filter = false;
  }

// Handle PD
if (RemoteXY.switchPD) {
    // Normierte Slider-Werte (0.0 - 1.0)
    float normKp = RemoteXY.sliderKp / 100.0f;
    float normKd = RemoteXY.sliderKd / 100.0f;

    // Logarithmische Skalierung
    RemoteXY.valueKp = 0.01f  * powf(10.0f, normKp * 3.0f);   // 0.01 ... 10
    RemoteXY.valueKd = 0.001f * powf(10.0f, normKd * 3.0f);   // 0.001 ... 1
    pidValue = loadcell.getPid(RemoteXY.valueKp, RemoteXY.valueKd);
    RemoteXY.onlineGraphPD = pidValue;
    pid = true;
}
else {
    RemoteXY.onlineGraphPD = 0;
    RemoteXY.sliderKp = 0;
    RemoteXY.sliderKd = 0;
    pid = false;
}

if (pid == true){
  dac.setDigitalData(pidValue);
}
else if (filter == true){
  dac.setDigitalData(filterValue);
}
else if (raw == true){
  dac.setDigitalData(rawValue);
}
else dac.setDigitalData(0);

  //CALIBRATION//
  if (RemoteXY.switchStartCal){
      strcpy(RemoteXY.textCalibration, startText);
      start = true;
  }

  if(RemoteXY.switch_Standing){
      if (start == true){
        RemoteXY.switchStartCal = 0;
        loadcell.tareZero();
        strcpy(RemoteXY.textCalibration, tareText);
        tared = true;
      }
      else {
        strcpy(RemoteXY.textCalibration, ErrorCalOrder);
        RemoteXY.switch_Standing = 0;
      }

  }

  if(RemoteXY.switch_Hanging){
    if (tared == true){
      RemoteXY.switch_Standing = 0;
      loadcell.calibrate();
      strcpy(RemoteXY.textCalibration, doneText);
      RemoteXY.switch_Hanging = 0;
      start = false;
      tared = false;
    }
    else {
      strcpy(RemoteXY.textCalibration, ErrorCalOrder);
      RemoteXY.switch_Hanging = 0;
    }
  }
  //CALIBRATION END//

  // Handle Encoder  --------------- Test show DAC analog output

  dacInput = dac.getAnalogData(dacInputPin);
  setHTAValues(dacInput);

  if (RemoteXY.switchLeft){

    RemoteXY.onlineGraphLeftVel = dacInput;
  }

  else RemoteXY.onlineGraphLeftVel = 0;

  //Handle right encoder
  if (RemoteXY.switchRight){
    RemoteXY.onlineGraphRightVel = rightMotorEncoder.getLinearVelocity();
  }
  else RemoteXY.onlineGraphRightVel = 0;


  }
  


  // TODO you loop code
  // use the RemoteXY structure for data transfer
  // do not call delay(), use instead RemoteXY_delay() 





